let libraryAlbums=[],currentView='albums',openedAlbum='',songLimit=50;
let albumPlaylist=[],albumPlayIndex=0,albumPlayTitle='',albumPlayId='',albumAutoAdvance=false;
let originalPlaylist=[],shuffleEnabled=false,nowPlayingSignature='';
const player=$('albumPlayer');
function playerIcon(name){const shapes={play:'<path d="M8 5v14l11-7z"/>',pause:'<path d="M7 5h4v14H7zm6 0h4v14h-4z"/>',previous:'<path d="M5 5h3v14H5zm14 0v14L8 12z"/>',next:'<path d="M16 5h3v14h-3zM5 5l11 7-11 7z"/>',stop:'<rect x="6" y="6" width="12" height="12" rx="1"/>'};return `<svg viewBox="0 0 24 24" width="21" height="21" fill="currentColor" aria-hidden="true">${shapes[name]}</svg>`;}
for(const [id,icon] of Object.entries({albumPrevious:'previous',albumNext:'next',albumToggle:'play',albumStop:'stop'}))$(id).innerHTML=playerIcon(icon);
function action(text,fn,cls){const b=node('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;}
function showView(view,writeHash=true){if(!['albums','tracks','create','album-create','album'].includes(view))view='albums';currentView=view;for(const [key,id] of Object.entries({albums:'albumsView',tracks:'tracksView',create:'createView','album-create':'albumCreateView',album:'albumView'}))$(id).hidden=key!==view;for(const b of document.querySelectorAll('.app-nav [data-view]')){if(b.dataset.view===(view==='album'?'albums':view))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if(writeHash){const hash=view==='album'?`#album/${openedAlbum}`:`#${view}`;if(location.hash!==hash)history.pushState(null,'',hash);}window.scrollTo({top:0,behavior:'instant'});}
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>showView(b.dataset.view));
function route(){const [view,id]=location.hash.slice(1).split('/');if(view==='album'&&id)openedAlbum=id;showView(view||'albums',false);if(view==='album')renderAlbumDetail();}
window.addEventListener('hashchange',route);$('backAlbums').addEventListener('click',()=>showView('albums'));
function albumForSong(id){return libraryAlbums.find(a=>a.songs?.some(s=>s?.id===id));}
function artwork(album,cls=''){const box=node('div',undefined,`artwork ${cls}`);if(album?.cover_url){const img=document.createElement('img');img.src=album.cover_url;img.alt='';img.loading='lazy';box.append(img);}else box.append(node('span','♫'));return box;}
function openAlbum(id){openedAlbum=id;renderAlbumDetail();showView('album');}
function renderLibrary(){renderAlbums();renderSongs();if(openedAlbum)renderAlbumDetail();updateAlbumControls();}
function renderAlbums(){const query=$('albumSearch').value.trim().toLocaleLowerCase();const albums=libraryAlbums.filter(a=>a.title.toLocaleLowerCase().includes(query));$('albumCountLabel').textContent=`${libraryAlbums.length}枚のアルバム · あなたの音楽を、ゆっくり聴こう。`;$('albums').replaceChildren(...albums.map(a=>{const card=node('article',undefined,'album-tile');const open=action('',()=>openAlbum(a.id),'album-open');open.setAttribute('aria-label',`${a.title}を開く`);open.append(artwork(a),node('h2',a.title),node('p',`${a.completed} / ${a.request.track_count-(a.deleted_count||0)}曲 · ${engineLabel(a.request.engine)}`));card.append(open);if(a.completed){const play=action('▶',()=>playAlbum(a), 'album-quick-play');play.setAttribute('aria-label',`${a.title}を再生`);card.append(play);}if(a.status!=='completed')card.append(node('span',albumLabels[a.status]||a.status,'album-badge'));return card;}));if(!albums.length)$('albums').append(node('p',query?'一致するアルバムはありません。':'まだアルバムがありません。「新しいアルバム」から作れます。','empty'));}
function filteredSongs(){const q=$('songSearch').value.trim().toLocaleLowerCase(),filter=$('songFilter').value;const songs=librarySongs.filter(j=>(!q||`${j.title} ${albumForSong(j.id)?.title||''}`.toLocaleLowerCase().includes(q))&&(filter==='all'||(filter==='completed'?j.status==='completed':filter==='active'?['queued','running','preparing'].includes(j.status):j.engine===filter)));songs.sort($('songSort').value==='title'?(a,b)=>a.title.localeCompare(b.title,'ja'):$('songSort').value==='old'?(a,b)=>a.created_at-b.created_at:(a,b)=>b.created_at-a.created_at);return songs;}
function renderSongs(){const songs=filteredSongs();const ready=librarySongs.some(j=>j.audio_url);$('playAll').disabled=!ready;$('shuffleAll').disabled=!ready;$('songCount').textContent=`${librarySongs.length}曲${songs.length!==librarySongs.length?` · ${songs.length}曲を表示`:''}`;$('songs').replaceChildren(...songs.slice(0,songLimit).map((j,i)=>trackRow(j,i,songs)));if(!songs.length)$('songs').append(node('p','該当する曲はありません。検索や絞り込みを変更してください。','empty'));$('moreSongs').hidden=songs.length<=songLimit;}
function trackRow(j,index,queue,album){const row=node('article',undefined,'track-row');row.dataset.song=j.id;const play=action('▶',()=>playSongs(queue,j.id,album?.title||'すべての曲',album?.id||''),'track-play');play.disabled=!j.audio_url;play.setAttribute('aria-label',`${j.title}を再生`);row.append(play);const text=node('div',undefined,'track-name');text.append(node('strong',j.title));const parent=album||albumForSong(j.id);text.append(node('small',j.status==='completed'?(parent?.title||'シングル')+' · '+(engineLabel(j.engine)):labels[j.status]||j.status));row.append(text,node('span',j.summary?.audio_seconds?duration(j.summary.audio_seconds):'—','track-duration'));const menu=node('details',undefined,'track-menu'),summary=node('summary','•••');summary.setAttribute('aria-label',`${j.title}の操作`);menu.append(summary);const content=node('div',undefined,'track-menu-content');if(j.derivation)content.append(action(`元曲：${j.derivation.source_title}`,()=>{menu.open=false;showDetail(j.derivation.source_song_id).catch(e=>notify(e.message,true));}));if(j.audio_url){content.append(action('MuLaCoverでカバーを作る',()=>{menu.open=false;startDerivative(j.id,'mulacover');}),action('DiffSynthで音色を参照',()=>{menu.open=false;startDerivative(j.id,'diffsynth');}));content.append(action('この曲から派生',()=>{menu.open=false;startDerivative(j.id);}));content.append(link(`${(j.audio_format||'audio').toUpperCase()}をダウンロード`,j.audio_url));const format=document.createElement('select');format.setAttribute('aria-label','変換先の保存形式');for(const value of ['m4a','flac']){const o=node('option',value.toUpperCase());o.value=value;format.append(o);}format.value=j.audio_format==='flac'?'m4a':'flac';content.append(format,action('保存形式を変更',async e=>{e.currentTarget.disabled=true;try{await api(`/api/songs/${j.id}/storage`,{format:format.value});await refreshSongs();notify('保存形式を変更しました。');}catch(e){notify(e.message,true);}finally{e.target.disabled=false;}}));}content.append(action('詳細を見る',()=>{menu.open=false;showDetail(j.id).catch(e=>notify(e.message,true));}),action('入力を再利用',async()=>{try{const d=await api(`/api/songs/${j.id}`);if(($('lyrics').value.trim()||$('style').value.trim())&&!confirm('現在の入力を、この曲の生成条件に置き換えますか？'))return;fillSong(d.input);showView('create');menu.open=false;}catch(e){notify(e.message,true);}}));if(['queued','preparing','running'].includes(j.status))content.append(action('生成をキャンセル',async()=>{try{await api(`/api/songs/${j.id}/cancel`,{});await refreshSongs();}catch(e){notify(e.message,true);}}));if(!['queued','preparing','running'].includes(j.status))content.append(action('曲を削除',()=>deleteLibrarySong(j),'danger-action'));menu.append(content);menu.addEventListener('toggle',()=>{if(menu.open)for(const other of document.querySelectorAll('.track-menu[open]'))if(other!==menu)other.open=false;});row.append(menu);return row;}
function renderAlbumDetail(){const album=libraryAlbums.find(a=>a.id===openedAlbum);if(!album){$('albumContent').replaceChildren(node('p','アルバムを読み込んでいます…'));return;}const head=node('div',undefined,'album-hero'),text=node('div');text.append(node('p','ALBUM','eyebrow'),node('h1',album.title),node('p',`${album.completed} / ${album.request.track_count-(album.deleted_count||0)}曲 · ${albumLabels[album.status]||album.status}`));if(album.plan)text.append(node('p',album.plan.concept,'album-concept'));const actions=node('div',undefined,'album-actions');if(album.completed)actions.append(action('▶ アルバムを再生',()=>playAlbum(album),'primary'),action('シャッフル再生',()=>playAlbum(album,null,true)));if(['planning','generating'].includes(album.status))actions.append(albumAction('生成を一時停止',`/api/albums/${album.id}/pause`));if(['paused','failed'].includes(album.status))actions.append(albumAction('生成を再開',`/api/albums/${album.id}/resume`));if(album.status==='completed'&&album.cover_status!=='generating')actions.append(link('アルバムをダウンロード',`/api/albums/${album.id}/download`));const extra=node('div',undefined,'album-actions album-management');extra.append(action('名前を変更',()=>manageAlbum(album,'rename')),action(album.cover_file?'ジャケットを再生成':'ジャケットを生成',()=>manageAlbum(album,'cover')),action('動画・YouTube投稿',()=>manageAlbum(album,'video')));if(album.cover_status==='generating')text.append(node('p','ジャケットを生成中…'));if(album.error||album.cover_error)text.append(node('p',album.error||album.cover_error,'song-error'));if(album.video_status==='generating')text.append(node('p','投稿用の動画を書き出し中…'));if(album.youtube?.status==='uploading')text.append(node('p',`YouTubeに送信中… ${album.youtube.progress||0}%`));text.append(actions,extra);head.append(artwork(album),text);const tracks=node('div',undefined,'album-track-list');for(const [i,t] of (album.plan?.tracks||[]).entries()){if(album.deleted_tracks?.includes(i))continue;const song=album.songs[i];if(song){const row=trackRow(song,i,album.songs.filter(Boolean),album);if(t.engine_reason)row.title=t.engine_reason;tracks.append(row);}else {const row=node('div',undefined,'track-row');row.append(node('span',String(i+1),'pending-number'),node('div',t.title,'track-name'),node('small',`生成待ち · ${duration(t.duration||album.request.duration)}${(t.engine||album.request.engine)==='yue2'?'（目安）':''} · ${engineLabel(t.engine||album.request.engine)}`));tracks.append(row);}if(t.engine_reason)tracks.append(node('p',`${engineLabel(t.engine||album.request.engine)}：${t.engine_reason}`,'small'));}const research=node('div',undefined,'reference-research');renderReferenceResearch(research,album.reference_research);$('albumContent').replaceChildren(head,research,tracks);}
for(const id of ['songSearch','songFilter','songSort'])$(id).addEventListener('input',()=>{songLimit=50;renderSongs();updateAlbumControls();});$('albumSearch').addEventListener('input',renderAlbums);$('moreSongs').addEventListener('click',()=>{songLimit+=50;renderSongs();updateAlbumControls();});
function shuffled(songs){const result=[...songs];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
function playSongs(songs,startId,title,id='',shuffle=false){originalPlaylist=songs.filter(j=>j?.audio_url);if(!originalPlaylist.length)return;shuffleEnabled=shuffle;albumPlaylist=shuffle?shuffled(originalPlaylist):[...originalPlaylist];albumPlayIndex=Math.max(0,albumPlaylist.findIndex(j=>j.id===startId));albumPlayTitle=title;albumPlayId=id;playAlbumTrack();}
function playAlbum(album,startId,shuffle=false){playSongs(album.songs,startId,album.title,album.id,shuffle);}
function syncAlbumPlaylist(albums){if(!albumPlayId)return;const a=albums.find(a=>a.id===albumPlayId),current=albumPlaylist[albumPlayIndex]?.id;if(!a)return;const ready=a.songs.filter(j=>j?.audio_url);if(!ready.some(j=>j.id===current))return;originalPlaylist=ready;if(shuffleEnabled){const ids=new Set(albumPlaylist.map(j=>j.id));albumPlaylist=[...albumPlaylist.map(j=>ready.find(r=>r.id===j.id)||j),...shuffled(ready.filter(j=>!ids.has(j.id)))];}else albumPlaylist=[...ready];albumPlayIndex=albumPlaylist.findIndex(j=>j.id===current);updateAlbumControls();if(!$('queuePanel').hidden)renderQueue();}
$('playAll').addEventListener('click',()=>playSongs([...librarySongs].sort((a,b)=>b.created_at-a.created_at),null,'すべての曲'));
$('shuffleAll').addEventListener('click',()=>playSongs(librarySongs,null,'すべての曲','',true));
$('shuffleToggle').innerHTML='<svg viewBox="0 0 24 24" width="21" height="21" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 6h3c5 0 7 12 12 12h3m-4-4 4 4-4 4M3 18h3c2 0 3-2 4-4m4-4c1-2 2-4 4-4h3m-4-4 4 4-4 4"/></svg>';
$('shuffleToggle').addEventListener('click',()=>{if(!albumPlaylist.length)return;const current=albumPlaylist[albumPlayIndex].id;shuffleEnabled=!shuffleEnabled;if(shuffleEnabled){albumPlaylist=[...albumPlaylist.slice(0,albumPlayIndex+1),...shuffled(albumPlaylist.slice(albumPlayIndex+1))];}else{albumPlaylist=[...originalPlaylist];albumPlayIndex=albumPlaylist.findIndex(j=>j.id===current);}updateAlbumControls();renderQueue();});
function updateAlbumControls(){publishNowPlaying();$('shuffleToggle').setAttribute('aria-pressed',String(shuffleEnabled));const j=albumPlaylist[albumPlayIndex];if(!j)return;$('albumNow').textContent=j.title;$('nowContext').textContent=`${albumPlayTitle} · ${albumPlayIndex+1} / ${albumPlaylist.length}`;$('albumPrevious').disabled=albumPlayIndex===0;$('albumNext').disabled=albumPlayIndex===albumPlaylist.length-1;const paused=player.paused;$('albumToggle').innerHTML=playerIcon(paused?'play':'pause');$('albumToggle').setAttribute('aria-label',paused?'再生':'一時停止');$('albumToggle').title=paused?'再生':'一時停止';for(const row of document.querySelectorAll('.track-row')){row.classList.toggle('is-playing',row.dataset.song===j.id);const b=row.querySelector('.track-play');if(b)b.textContent=row.dataset.song===j.id&&!paused?'♫':'▶';}if('mediaSession' in navigator)navigator.mediaSession.playbackState=paused?'paused':'playing';}
function renderQueue(){$('queueTracks').replaceChildren(...albumPlaylist.map((j,i)=>{const b=action(`${i+1}. ${j.title}`,()=>{albumPlayIndex=i;playAlbumTrack();});if(i===albumPlayIndex)b.setAttribute('aria-current','true');return b;}));}
function playAlbumTrack(){const j=albumPlaylist[albumPlayIndex];if(!j)return;albumAutoAdvance=true;$('albumPlayback').hidden=false;document.body.classList.add('album-is-open');player.src=j.audio_url;$('nowArt').replaceChildren(artwork(albumForSong(j.id)));updateAlbumControls();renderQueue();updateProgress();publishNowPlaying();player.play().catch(e=>{if(e.name!=='AbortError')notify('再生ボタンを押して試聴してください。');});}
function stopAlbum(){albumAutoAdvance=false;player.pause();player.currentTime=0;updateAlbumControls();updateProgress();}
function nextTrack(offset){if(albumPlayIndex+offset>=0&&albumPlayIndex+offset<albumPlaylist.length){albumPlayIndex+=offset;playAlbumTrack();}}
function togglePlayback(){if(!albumPlaylist.length)return;if(player.paused)player.play().catch(()=>notify('再生できませんでした',true));else player.pause();}
function updateProgress(){const len=Number.isFinite(player.duration)?player.duration:0;$('elapsed').textContent=duration(player.currentTime||0);$('trackLength').textContent=duration(len);$('seek').disabled=!len;$('seek').max=len||100;$('seek').value=player.currentTime||0;$('seek').setAttribute('aria-valuetext',`${duration(player.currentTime||0)} / ${duration(len)}`);}
player.volume=.8;player.addEventListener('ended',()=>{if(albumAutoAdvance&&albumPlayIndex+1<albumPlaylist.length)nextTrack(1);else{albumAutoAdvance=false;updateAlbumControls();}});player.addEventListener('play',()=>{albumAutoAdvance=true;updateAlbumControls();});player.addEventListener('pause',updateAlbumControls);player.addEventListener('error',()=>notify('音声を読み込めませんでした。曲を選び直してください。',true));for(const type of ['timeupdate','loadedmetadata','durationchange'])player.addEventListener(type,updateProgress);
$('albumToggle').addEventListener('click',togglePlayback);$('albumStop').addEventListener('click',stopAlbum);$('albumNext').addEventListener('click',()=>nextTrack(1));$('albumPrevious').addEventListener('click',()=>nextTrack(-1));$('albumClose').addEventListener('click',()=>{stopAlbum();$('albumPlayback').hidden=true;$('queuePanel').hidden=true;$('queueToggle').setAttribute('aria-expanded','false');document.body.classList.remove('album-is-open');});$('seek').addEventListener('input',()=>{if(Number.isFinite(player.duration))player.currentTime=Number($('seek').value);updateProgress();});$('volume').addEventListener('input',()=>{player.volume=Number($('volume').value);});$('queueToggle').addEventListener('click',()=>{$('queuePanel').hidden=!$('queuePanel').hidden;$('queueToggle').setAttribute('aria-expanded',String(!$('queuePanel').hidden));renderQueue();});$('queueClose').addEventListener('click',()=>{$('queuePanel').hidden=true;$('queueToggle').setAttribute('aria-expanded','false');$('queueToggle').focus();});
document.addEventListener('click',e=>{for(const menu of document.querySelectorAll('.track-menu[open]'))if(!menu.contains(e.target))menu.open=false;});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!e.target.closest('input,textarea,select,button,a,summary,[contenteditable],dialog')&&!$('albumPlayback').hidden){e.preventDefault();togglePlayback();}if(e.key==='Escape'){$('queuePanel').hidden=true;$('queueToggle').setAttribute('aria-expanded','false');for(const menu of document.querySelectorAll('.track-menu[open]'))menu.open=false;}});
if('mediaSession' in navigator)for(const [name,fn] of Object.entries({play:()=>player.play(),pause:()=>player.pause(),previoustrack:()=>nextTrack(-1),nexttrack:()=>nextTrack(1),stop:stopAlbum,seekto:e=>{if(Number.isFinite(player.duration))player.currentTime=e.seekTime;}})){try{navigator.mediaSession.setActionHandler(name,fn);}catch{}}
route();renderSongs();

function publishNowPlaying(){if(!('mediaSession' in navigator)||!('MediaMetadata' in window))return;const song=albumPlaylist[albumPlayIndex];if(!song)return;const album=albumForSong(song.id);const cover=new URL(album?.cover_url||'/static/app-icon.png',location.href).href;const metadata={title:song.title,artist:'OTONI',album:album?.title||'シングル',artwork:[{src:cover}]};const signature=JSON.stringify(metadata);if(signature===nowPlayingSignature)return;try{navigator.mediaSession.metadata=new MediaMetadata(metadata);nowPlayingSignature=signature;}catch{}}

async function deleteLibrarySong(song){
  if(!confirm(`「${song.title}」を削除しますか？\n音声・歌詞・生成条件を削除します。元に戻せません。`))return;
  try{await api(`/api/songs/${song.id}/delete`,{title:song.title});
    const current=albumPlaylist[albumPlayIndex]?.id,index=albumPlayIndex,wasPlaying=!player.paused;
    albumPlaylist=albumPlaylist.filter(j=>j.id!==song.id);originalPlaylist=originalPlaylist.filter(j=>j.id!==song.id);
    if(current===song.id){player.pause();player.removeAttribute('src');player.load();
      if(albumPlaylist.length){albumPlayIndex=Math.min(index,albumPlaylist.length-1);if(wasPlaying)playAlbumTrack();else{player.src=albumPlaylist[albumPlayIndex].audio_url;updateAlbumControls();updateProgress();}}
      else{$('albumPlayback').hidden=true;document.body.classList.remove('album-is-open');albumAutoAdvance=false;albumPlayId='';if('mediaSession' in navigator){navigator.mediaSession.metadata=null;navigator.mediaSession.playbackState='none';}nowPlayingSignature='';}
    }else albumPlayIndex=Math.max(0,albumPlaylist.findIndex(j=>j.id===current));
    renderQueue();if(selectedJob===song.id){selectedJob=null;$('jobDetail').close();}
    await refreshSongs();await refreshAlbums();notify(`「${song.title}」を削除しました。`);
  }catch(e){notify(e.message,true);}
}
